---

# DC Variables
dc_name: dc01
mgmt_gateway: 172.26.249.62/26

# Spines Variables
spine:
  defaults:
    platform: 7260X3
    bgp_as: 64520
    loopback_ipv4_pool: 10.253.0.0/24
    bgp_defaults: 
      - 'update wait-for-convergence'
      - 'update wait-install'
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    swex-dc01-sp01:
      id: 1
      mgmt_ip: 172.26.249.1/26
      evpn_route_servers: [swex-dc02-sp01, swex-dc02-sp02]
    swex-dc01-sp02:
      id: 2
      mgmt_ip: 172.26.249.1/26
      evpn_route_servers: [swex-dc02-sp01, swex-dc02-sp02]

 # Leaf Variables
l3leaf:
  defaults:
    platform: 7050SX3
    loopback_ipv4_pool: 10.253.0.0/24
    loopback_ipv4_offset: 4
    vtep_loopback_ipv4_pool: 10.253.1.0/24
    uplink_interfaces: ['Ethernet49/1', 'Ethernet50/1']
    uplink_switches: ['swex-dc01-sp01', 'swex-dc01-sp02']
    max_uplink_switches: 4
    uplink_ipv4_pool: 10.253.2.0/24
    mlag_peer_ipv4_pool: 10.253.4.0/24
    mlag_peer_l3_ipv4_pool: 10.253.3.0/24
    mlag_interfaces: [Ethernet55/1, Ethernet56/1]
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    virtual_router_mac_address: 00:1c:73:00:00:99
    bgp_defaults: 
      - 'update wait-for-convergence'
      - 'update wait-install'
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  node_groups:
    swex-dc01-bl01:
      bgp_as: 64559
      platform: 7050CX3
      uplink_interfaces: ['Ethernet1/1', 'Ethernet2/1']
      mlag_interfaces: [Ethernet31/1, Ethernet32/1]
      nodes:
        swex-dc01-bl01a:
          id: 1
          mgmt_ip: 172.26.249.3/26
          uplink_switch_interfaces: [Ethernet63/1, Ethernet63/1]
          
        swex-dc01-bl01b:
          id: 2
          mgmt_ip: 172.26.249.4/26
          uplink_switch_interfaces: [Ethernet64/1, Ethernet64/1]
    swex-dc01-le01:
      bgp_as: 64521
      nodes:
        swex-dc01-le01a:
          id: 3
          mgmt_ip: 172.26.249.11/26
          uplink_switch_interfaces: [Ethernet1/1, Ethernet1/1]
        swex-dc01-le01b:
          id: 4
          mgmt_ip: 172.26.249.12/26
          uplink_switch_interfaces: [Ethernet2/1, Ethernet2/1]
    swex-dc01-le02:
      bgp_as: 64522
      nodes:
        swex-dc01-le02a:
          id: 5
          mgmt_ip: 172.26.249.13/26
          uplink_switch_interfaces: [Ethernet3/1, Ethernet3/1]
        swex-dc01-le02b:
          id: 6
          mgmt_ip: 172.26.249.14/26
          uplink_switch_interfaces: [Ethernet4/1, Ethernet4/1]
    swex-dc01-le03:
      bgp_as: 64523
      nodes:
        swex-dc01-le03a:
          id: 7
          mgmt_ip: 172.26.249.15/26
          uplink_switch_interfaces: [Ethernet5/1, Ethernet5/1]
        swex-dc01-le03b:
          id: 8
          mgmt_ip: 172.26.249.16/26
          uplink_switch_interfaces: [Ethernet6/1, Ethernet6/1]
    swex-dc01-le04:
      bgp_as: 64524
      nodes:
        swex-dc01-le04a:
          id: 9
          mgmt_ip: 172.26.249.17/26
          uplink_switch_interfaces: [Ethernet7/1, Ethernet7/1]
        swex-dc01-le04b:
          id: 10
          mgmt_ip: 172.26.249.18/26
          uplink_switch_interfaces: [Ethernet8/1, Ethernet8/1]
    swex-dc01-le05:
      bgp_as: 64525
      nodes:
        swex-dc01-le05a:
          id: 11
          mgmt_ip: 172.26.249.19/26
          uplink_switch_interfaces: [Ethernet9/1, Ethernet9/1]
        swex-dc01-le05b:
          id: 12
          mgmt_ip: 172.26.249.20/26
          uplink_switch_interfaces: [Ethernet10/1, Ethernet10/1]

# BFD
bfd_multihop:
  interval: 300
  min_rx: 300
  multiplier: 3

# BGP Peer Groups
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "+lBCLt9VnYcg03kK0esQwg=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "IWPc0FZNVdXHq/ScCuikjA=="
  EVPN_OVERLAY_PEERS:
    password: "bIdYFtUM5l/dNEzAHZy5BA=="

### TERMINATTR (CVP telemetry) ###
cs_dh01_daemon_terminattr:
  ingestgrpcurl:
    ips:
      - 10.59.56.154
    port: 9910
  ingestauth_key: cvpTel45Ing38key
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  ingestvrf: MGMT





      

