---

# DC Variables
dc_name: dc02
mgmt_gateway: 172.26.249.190/26

# Spines Variables
spine:
  defaults:
    platform: 7260X3
    bgp_as: 64560
    loopback_ipv4_pool: 10.253.16.0/24
    bgp_defaults: 
      - 'update wait-for-convergence'
      - 'update wait-install'
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    swex-dc02-sp01:
      id: 1
      mgmt_ip: 172.26.249.129/26
      evpn_route_servers: [swex-dc01-sp01, swex-dc01-sp02]
    swex-dc02-sp02:
      id: 2
      mgmt_ip: 10.62.37.130/25
      evpn_route_servers: [swex-dc01-sp01, swex-dc01-sp02]

 # Leaf Variables
l3leaf:
  defaults:
    platform: 7050SX3
    loopback_ipv4_pool: 10.253.16.0/24
    loopback_ipv4_offset: 4
    vtep_loopback_ipv4_pool: 10.253.17.0/24
    uplink_interfaces: ['Ethernet49/1', 'Ethernet50/1']
    uplink_switches: ['swex-dc02-sp01', 'swex-dc02-sp02']
    max_uplink_switches: 4
    uplink_ipv4_pool: 10.253.18.0/24
    mlag_peer_ipv4_pool: 10.253.20.0/24
    mlag_peer_l3_ipv4_pool: 10.253.19.0/24
    mlag_interfaces: [Ethernet55/1, Ethernet56/1]
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    virtual_router_mac_address: 00:1c:73:00:00:99
    bgp_defaults: 
      - 'update wait-for-convergence'
      - 'update wait-install'
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  node_groups:
    swex-dc02-bl01:
      bgp_as: 64599
      platform: 7050CX3
      nodes:
        swex-dc02-bl01a:
          id: 1
          mgmt_ip: 172.26.249.131/26
          uplink_switch_interfaces: [Ethernet63/1, Ethernet63/1]
          mlag_interfaces: [Ethernet31/1, Ethernet32/1]
        swex-dc02-bl01b:
          id: 2
          mgmt_ip: 172.26.249.132/26
          uplink_switch_interfaces: [Ethernet64/1, Ethernet64/1]
          mlag_interfaces: [Ethernet31/1, Ethernet32/1]
    swex-dc02-le01:
      bgp_as: 64561
      nodes:
        swex-dc02-le01a:
          id: 3
          mgmt_ip: 172.26.249.141/26
          uplink_switch_interfaces: [Ethernet1/1, Ethernet1/1]
        swex-dc02-le01b:
          id: 4
          mgmt_ip: 172.26.249.142/26
          uplink_switch_interfaces: [Ethernet2/1, Ethernet2/1]
    swex-dc02-le02:
      bgp_as: 64562
      nodes:
        swex-dc02-le02a:
          id: 5         
          mgmt_ip: 172.26.249.143/26
          uplink_switch_interfaces: [Ethernet3/1, Ethernet3/1]
        swex-dc02-le02b:
          id: 6
          mgmt_ip: 172.26.249.144/26
          uplink_switch_interfaces: [Ethernet4/1, Ethernet4/1]
    swex-dc02-le03:
      bgp_as: 64563
      nodes:
        swex-dc02-le03a:
          id: 7         
          mgmt_ip: 172.26.249.145/26
          uplink_switch_interfaces: [Ethernet5/1, Ethernet5/1]
        swex-dc02-le03b:
          id: 8
          mgmt_ip: 172.26.249.146/26
          uplink_switch_interfaces: [Ethernet6/1, Ethernet6/1]
    swex-dc02-le04:
      bgp_as: 64564
      nodes:
        swex-dc02-le04a:
          id: 9         
          mgmt_ip: 172.26.249.147/26
          uplink_switch_interfaces: [Ethernet7/1, Ethernet7/1]
        swex-dc02-le04b:
          id: 10
          mgmt_ip: 172.26.249.148/26
          uplink_switch_interfaces: [Ethernet8/1, Ethernet8/1]
    swex-dc02-le05:
      bgp_as: 64565
      nodes:
        swex-dc02-le05a:
          id: 11         
          mgmt_ip: 172.26.249.149/26
          uplink_switch_interfaces: [Ethernet9/1, Ethernet9/1]
        swex-dc02-le05b:
          id: 12
          mgmt_ip: 172.26.249.150/26
          uplink_switch_interfaces: [Ethernet10/1, Ethernet10/1]

# BFD
bfd_multihop:
  interval: 300
  min_rx: 300
  multiplier: 3

# BGP Peer Groups
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "+lBCLt9VnYcg03kK0esQwg=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "IWPc0FZNVdXHq/ScCuikjA=="
  EVPN_OVERLAY_PEERS:
    password: "bIdYFtUM5l/dNEzAHZy5BA=="

### TERMINATTR (CVP telemetry) ###
cs_dh01_daemon_terminattr:
  ingestgrpcurl:
    ips:
      - 10.59.56.154
    port: 9910
  ingestauth_key: cvpTel45Ing38key
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  ingestvrf: MGMT
