all:
  children:
    cloudvision:
      hosts:
        cvp-lab.acmed2.com:
      vars:
        ansible_connection: httpapi
        ansible_httpapi_use_ssl: True
        ansible_httpapi_validate_certs: False
        ansible_user: cvpadmin
        ansible_password: acmelabb
        ansible_network_os: eos
        ansible_httpapi_port: 443
    acme_fabric:
      children:
        dc01_fabric:
          children:
            dc01_spine:
              hosts:
                swex-dc01-sp01:
                swex-dc01-sp02:
            dc01_border:
              hosts:
                swex-dc01-bl01a:
                swex-dc01-bl01b:
              vars:
                type: l3leaf
            dc01_leaf:
              hosts:
                swex-dc01-le01a:
                swex-dc01-le01b:
                swex-dc01-le02a:
                swex-dc01-le02b:
                swex-dc01-le03a:
                swex-dc01-le03b:
                swex-dc01-le04a:
                swex-dc01-le04b:
                swex-dc01-le05a:
                swex-dc01-le05b:
              vars:
                type: l3leaf
            dc01_compute:
              children:
                dc01_leaf:
            dc01_edge:
              children:
                dc01_border:
        dc02_fabric:
          children:
            dc02_spine:
              hosts:
                swex-dc02-sp01:
                swex-dc02-sp02:
            dc02_border:
              hosts:
                swex-dc02-bl01a:
                swex-dc02-bl01b:
              vars:
                type: l3leaf
            dc02_leaf:
              hosts:
                swex-dc02-le01a:
                swex-dc02-le01b:
                swex-dc02-le02a:
                swex-dc02-le02b:
                swex-dc02-le03a:
                swex-dc02-le03b:
                swex-dc02-le04a:
                swex-dc02-le04b:
                swex-dc02-le05a:
                swex-dc02-le05b:
              vars:
                type: l3leaf
            dc02_compute:
              children:
                dc02_leaf:
            dc02_edge:
              children:
                dc02_border:
        dh01_fabric:
          children:
            dh01_spine:
              hosts:
                swex-dh01-sp01:
                swex-dh01-sp02:
            dh01_border:
              hosts:
                swex-dh01-bl01a:
                swex-dh01-bl01b:
              vars:
                type: l3leaf
            dh01_leaf:
              children:
                dh01_leaf01:
                dh01_leaf02:
              vars:
                type: l3leaf
            dh01_leaf01:
              hosts:
                swex-dh01-le01a:
                swex-dh01-le01b:
            dh01_leaf02:
              hosts:
                swex-dh01-le02a:
                swex-dh01-le02b:
            dh01_compute:
              children:
                dh01_leaf:
                dh01_border:
            dh01_edge:
              children:
                dh01_border:
        all_spines:
          children:
            dh01_spine:
            dc01_spine:
            dc02_spine:
          vars:
            type: spine
        dc_fabric:
          children:
            dc01_fabric:
            dc02_fabric:

      vars:
        ansible_user: admin
        ansible_ssh_pass: acme
        ansible_network_os: eos
        ansible_connection: httpapi
        ansible_become: yes
        ansible_become_method: enable
  vars:
    ansible_python_interpreter: "python3"
