---

- name: Deprecation warning!
  delegate_to: localhost
  debug:
    msg:
      - "!!! Deprecation Warning - Please note this role has been replaced with arista.avd.eos_designs role."
      - "!!! Deprecation Warning - Please update your playbook accordingly."
      - "!!! Deprecation Warning - This role will be removed in version 3.0.0."
      - "!!! Deprecation Warning - Importing role: arista.avd.eos_designs ..."
  run_once: true

- name: import new role eos_designs
  import_role:
    name: arista.avd.eos_designs
