router_bgp:
  as: 65101
  router_id: 192.168.255.3
  bgp_defaults:
    - no bgp default ipv4-unicast
    - distance bgp 20 200 200
    - graceful-restart restart-time 300
    - graceful-restart
    - maximum-paths 2 ecmp 2
  bgp:
    bestpath:
      d_path: true
  aggregate_addresses:
    1.1.1.0/24:
      advertise_only: true
    2.2.1.0/24:
    1.12.1.0/24:
      as_set: true
      summary_only: true
      attribute_map: RM-ATTRIBUTE
      match_map: RM-MATCH
      advertise_only: true
  address_family_ipv4:
    networks:
      10.0.0.0/8:
      172.16.0.0/12:
      192.168.0.0/16:
        route_map: RM-FOO-MATCH
    peer_groups:
      foo:
        prefix_list_in: PL-BAR-v4-IN
        prefix_list_out: PL-BAR-v4-OUT
        default_originate:
          always: true
          route_map: RM-FOO-MATCH
    neighbors:
      192.0.2.1:
        prefix_list_in: PL-FOO-v4-IN
        prefix_list_out: PL-FOO-v4-OUT

  address_family_ipv6:
    networks:
      2001:db8:100::/40:
      2001:db8:200::/40:
        route_map: RM-BAR-MATCH
    peer_groups:
      baz:
        prefix_list_in: PL-BAR-v6-IN
        prefix_list_out: PL-BAR-v6-OUT
    neighbors:
      2001:db8::1:
        prefix_list_in: PL-FOO-v6-IN
        prefix_list_out: PL-FOO-v6-OUT

